from PyQt6.QtGui import QColor, QMouseEvent, QPaintEvent
from PyQt6.QtWidgets import QWidget
from _typeshed import Incomplete

class Led(QWidget):
    on: bool
    light_color: Incomplete
    glow_effect: Incomplete
    _parent: Incomplete
    def __init__(self, parent: QWidget | None = None) -> None: ...
    def isOn(self) -> bool: ...
    def setOn(self, on: bool) -> None: ...
    def getLightColor(self) -> QColor: ...
    def mouseReleaseEvent(self, e: QMouseEvent | None) -> None: ...
    def setLightColor(self, color: QColor) -> None: ...
    def paintEvent(self, event: QPaintEvent | None) -> None: ...
